name: barcode_pplication
description: "A new Flutter project."
publish_to: 'none'
environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.25.4
  cupertino_icons: ^1.0.2
  simple_barcode_scanner: ^0.1.0
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
